export enum RoleProfileExternal {
  FOPS_CUSTOMER_B2C = 6,
  FOPS_ADMINISTRADORTECNICO = 5,
  FOPS_CONTRATISTA = 10,
}

export enum RoleProfileInternal {
  FOPS_CUSTOMER_B2C = 6,
  FOPS_EJECUTIVODEVENTAS = 7,
  FOPS_COORDINADOR = 8,
  FOPS_DISEÑADOR = 9,
}